# Generated by Django 2.2.5 on 2019-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ic', models.CharField(max_length=12)),
                ('transfer', models.CharField(default='Not transferred', max_length=200)),
                ('patientnumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientstatus', models.CharField(blank=True, choices=[('a', 'Active'), ('r', 'RIP'), ('m', 'MIA')], default='a', help_text='Patient status', max_length=1)),
            ],
        ),
    ]
